# Shared GPU build selection for the SDK, native demo and topology library.
# This configures existing shared sources; it does not establish numerical SDK
# acceptance. The repository build helper retains that explicit acceptance gate.
include_guard(GLOBAL)
set(PX_GPU_BACKEND "CUDA" CACHE STRING "GPU compiler: CUDA or CUMETAL")
set_property(CACHE PX_GPU_BACKEND PROPERTY STRINGS CUDA CUMETAL)
if(NOT PX_GPU_BACKEND MATCHES "^(CUDA|CUMETAL)$")
    message(FATAL_ERROR "PX_GPU_BACKEND must be CUDA or CUMETAL")
endif()
if(PX_CUMETAL_BLOCK_VOTED_TRAPS AND NOT PX_GPU_BACKEND STREQUAL "CUMETAL")
    message(FATAL_ERROR "PX_CUMETAL_BLOCK_VOTED_TRAPS requires PX_GPU_BACKEND=CUMETAL")
endif()
IF(PX_CUMETAL_PACK_BOND_STRESS_SCALARS AND NOT PX_GPU_BACKEND STREQUAL "CUMETAL")
    MESSAGE(FATAL_ERROR "PX_CUMETAL_PACK_BOND_STRESS_SCALARS requires PX_GPU_BACKEND=CUMETAL")
ENDIF()
IF(DEFINED PX_CUMETAL_PARTICLE_INLINE_THRESHOLD AND
   NOT "${PX_CUMETAL_PARTICLE_INLINE_THRESHOLD}" STREQUAL "" AND NOT PX_GPU_BACKEND STREQUAL "CUMETAL")
    MESSAGE(FATAL_ERROR "PX_CUMETAL_PARTICLE_INLINE_THRESHOLD requires PX_GPU_BACKEND=CUMETAL")
ENDIF()
IF(DEFINED PX_CUMETAL_SOFTBODY_INLINE_THRESHOLD AND
   NOT "${PX_CUMETAL_SOFTBODY_INLINE_THRESHOLD}" STREQUAL "" AND NOT PX_GPU_BACKEND STREQUAL "CUMETAL")
    MESSAGE(FATAL_ERROR "PX_CUMETAL_SOFTBODY_INLINE_THRESHOLD requires PX_GPU_BACKEND=CUMETAL")
ENDIF()
if(PX_CUMETAL_EXPLICIT_AGGREGATE_ROOT AND NOT PX_GPU_BACKEND STREQUAL "CUMETAL")
    message(FATAL_ERROR "PX_CUMETAL_EXPLICIT_AGGREGATE_ROOT requires PX_GPU_BACKEND=CUMETAL")
endif()
if(PX_CUMETAL_EXPLICIT_MOTION_ROOT AND NOT PX_GPU_BACKEND STREQUAL "CUMETAL")
    message(FATAL_ERROR "PX_CUMETAL_EXPLICIT_MOTION_ROOT requires PX_GPU_BACKEND=CUMETAL")
endif()
if(PX_CUMETAL_RIGID_DEMO AND NOT PX_GPU_BACKEND STREQUAL "CUMETAL")
    message(FATAL_ERROR "PX_CUMETAL_RIGID_DEMO requires PX_GPU_BACKEND=CUMETAL")
endif()
find_package(Threads REQUIRED)
if(APPLE)
    set(PX_DESTRUCTION_GC_SECTIONS "-Wl,-dead_strip")
    set(PX_DESTRUCTION_PLATFORM mac.arm64)
else()
    set(PX_DESTRUCTION_GC_SECTIONS "-Wl,--gc-sections")
    set(PX_DESTRUCTION_PLATFORM linux.x86_64)
endif()

if(PX_GPU_BACKEND STREQUAL "CUMETAL")
    if(NOT APPLE OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
        message(FATAL_ERROR "CuMetal destruction targets require macOS Apple Silicon")
    endif()
    foreach(required CUMETAL_ROOT_DIR CUMETALC_EXECUTABLE CUMETAL_LIBRARY CUMETAL_CUDA_CLANG)
        if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
            message(FATAL_ERROR "Missing local CuMetal prerequisite ${required}: ${${required}}. Use the repository build helper; no installer or download will run.")
        endif()
    endforeach()
    # Reuse the same source-first native-AOT compiler path as the GPU engine.
    # PHYSX_ROOT_DIR is the name expected by the shared compiler helper.
    set(PHYSX_ROOT_DIR "${PHYSX_ROOT}")
    include("${PHYSX_ROOT}/source/compiler/cmakegpu/mac/CuMetalObjects.cmake")
    if(NOT TARGET CuMetal::Runtime)
        add_library(CuMetal::Runtime SHARED IMPORTED GLOBAL)
        set_target_properties(CuMetal::Runtime PROPERTIES
            IMPORTED_LOCATION "${CUMETAL_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${CUMETAL_ROOT_DIR}/runtime/api")
    endif()
    set(PX_DESTRUCTION_GPU_RUNTIME CuMetal::Runtime)
    set(PX_DESTRUCTION_GPU_DRIVER CuMetal::Runtime)
    set(PX_DESTRUCTION_GPU_INCLUDE_DIRS "${CUMETAL_ROOT_DIR}/runtime/api")
    get_filename_component(PX_DESTRUCTION_RUNTIME_DIR "${CUMETAL_LIBRARY}" DIRECTORY)
    include_directories(BEFORE "${CUMETAL_ROOT_DIR}/runtime/api")
    if(PX_GENERATED_INCLUDE_DIR)
        include_directories(BEFORE "${PX_GENERATED_INCLUDE_DIR}")
    endif()
    # Match private header choices in physx/compiler/public. The safe helper
    # supplies the same option values to the engine and this package build.
    option(PX_CUMETAL_SPLIT_RESPONSE_STAMP "Use the ordered split-word response stamp" ON)
    option(PX_CUMETAL_SERIAL_CONTACT_IDS "Assign contact lifetimes in one ordered GPU block" ON)
    option(PX_CUMETAL_ENABLE_GPU_SDF_BUILDER "Compile optional GPU SDF construction" OFF)
    option(PX_CUMETAL_ENABLE_CONVEX_CORE "Compile optional ConvexCore geometry" OFF)
    set(PX_CUMETAL_TGS_WHOLE_ISLAND_MAX_BODIES "512" CACHE STRING "Shared TGS body/slab capacity")
    if(NOT "${PX_CUMETAL_TGS_WHOLE_ISLAND_MAX_BODIES}" MATCHES "^[1-9][0-9]*$" OR
       "${PX_CUMETAL_TGS_WHOLE_ISLAND_MAX_BODIES}" GREATER 944)
        message(FATAL_ERROR "PX_CUMETAL_TGS_WHOLE_ISLAND_MAX_BODIES must be an integer in [1, 944]")
    endif()
    set(PX_DESTRUCTION_CUMETAL_DEFINITIONS PX_CUMETAL=1
        PXG_TGS_WHOLE_ISLAND_MAX_BODIES=${PX_CUMETAL_TGS_WHOLE_ISLAND_MAX_BODIES})
    if(PX_CUMETAL_SPLIT_RESPONSE_STAMP)
        list(APPEND PX_DESTRUCTION_CUMETAL_DEFINITIONS PX_CUMETAL_SPLIT_RESPONSE_STAMP=1)
    endif()
    if(PX_CUMETAL_SERIAL_CONTACT_IDS)
        list(APPEND PX_DESTRUCTION_CUMETAL_DEFINITIONS PX_CUMETAL_SERIAL_CONTACT_IDS=1)
    endif()
    if(NOT PX_CUMETAL_ENABLE_GPU_SDF_BUILDER)
        list(APPEND PX_DESTRUCTION_CUMETAL_DEFINITIONS PX_CUMETAL_DISABLE_GPU_SDF_BUILDER=1)
    endif()
    if(NOT PX_CUMETAL_ENABLE_CONVEX_CORE)
        list(APPEND PX_DESTRUCTION_CUMETAL_DEFINITIONS PX_CUMETAL_DISABLE_CONVEX_CORE=1)
    endif()
    add_compile_definitions(${PX_DESTRUCTION_CUMETAL_DEFINITIONS})
else()
    # Only this branch enables or discovers an NVIDIA compiler/toolkit.
    set(PX_DESTRUCTION_GPU_DRIVER cuda)
    if(BLAST_ENABLE_CUDA_STRESS)
        if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
            set(CMAKE_CUDA_ARCHITECTURES 89 CACHE STRING "CUDA architectures for destruction kernels")
        endif()
        include(CheckLanguage)
        check_language(CUDA)
        if(NOT CMAKE_CUDA_COMPILER)
            message(FATAL_ERROR "CUDA stress requested but compiler unavailable; install CUDA >=12.8 manually or select an already installed compiler")
        endif()
        enable_language(CUDA)
        set(CMAKE_CUDA_STANDARD 17)
        set(CMAKE_CUDA_STANDARD_REQUIRED ON)
        find_package(CUDAToolkit 12.8 REQUIRED)
        set(PX_DESTRUCTION_GPU_RUNTIME CUDA::cudart)
        set(PX_DESTRUCTION_GPU_DRIVER CUDA::cuda_driver)
        set(PX_DESTRUCTION_GPU_INCLUDE_DIRS "${CUDAToolkit_INCLUDE_DIRS}")
    endif()
endif()

# CUDA properties are applied only with the NVIDIA language enabled. The
# CuMetal branch receives its numerical/resource options via native AOT.
function(px_destruction_cuda_properties target)
    if(PX_GPU_BACKEND STREQUAL "CUDA")
        set_target_properties(${target} ${ARGN})
    endif()
endfunction()

# Call after all sources, definitions and link dependencies in this directory
# are declared. This preserves every original target and numerical test body.
function(px_destruction_finalize_gpu_targets)
    if(NOT PX_GPU_BACKEND STREQUAL "CUMETAL")
        return()
    endif()
    get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(type ${target} TYPE)
        if(NOT type MATCHES "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY)$")
            continue()
        endif()
        target_compile_definitions(${target} PRIVATE ${PX_DESTRUCTION_CUMETAL_DEFINITIONS})
        get_target_property(sources ${target} SOURCES)
        foreach(source IN LISTS sources)
            if(source MATCHES "\\.cu$")
                px_cumetal_objects(${target})
                # The engine helper links its build-tree runtime by filename.
                # Exported static SDK libraries must reference the package
                # target instead, never retain that absolute build-tree path.
                foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
                    get_target_property(links ${target} ${property})
                    if(NOT links STREQUAL "links-NOTFOUND")
                        set(package_links)
                        foreach(link IN LISTS links)
                            if(link STREQUAL "${CUMETAL_LIBRARY}")
                                list(APPEND package_links CuMetal::Runtime)
                            elseif(link STREQUAL "$<LINK_ONLY:${CUMETAL_LIBRARY}>")
                                list(APPEND package_links "$<LINK_ONLY:CuMetal::Runtime>")
                            else()
                                list(APPEND package_links "${link}")
                            endif()
                        endforeach()
                        set_property(TARGET ${target} PROPERTY ${property} "${package_links}")
                    endif()
                endforeach()
                break()
            endif()
        endforeach()
        # Host CUDA-compatible APIs use the same runtime even on pure-C++ tests.
        target_include_directories(${target} PRIVATE "${CUMETAL_ROOT_DIR}/runtime/api")
        set_property(TARGET ${target} APPEND PROPERTY BUILD_RPATH "${PX_DESTRUCTION_RUNTIME_DIR}" "${PHYSX_LIB_DIR}")
        if(type MATCHES "^(SHARED_LIBRARY|MODULE_LIBRARY)$")
            set_property(TARGET ${target} APPEND PROPERTY INSTALL_RPATH "@loader_path")
        endif()
    endforeach()
    # Preserve test-specific environment settings and enforce the ordinary
    # asynchronous source-first execution mode. No per-kernel forced waits.
    get_property(tests DIRECTORY PROPERTY TESTS)
    foreach(test IN LISTS tests)
        set_property(TEST ${test} APPEND PROPERTY ENVIRONMENT
            "CUMETAL_USE_METAL_DEVICE_ADDRESSES=1" "CUMETAL_SYNC_EACH_LAUNCH=0")
        set_property(TEST ${test} PROPERTY RUN_SERIAL TRUE)
    endforeach()
endfunction()
